Inumedia/SlackAPI

Channel.cs
Group.cs
RPCMessages/GroupArchiveResponse.cs
RPCMessages/GroupCloseResponse.cs
RPCMessages/GroupCreateChildResponse.cs
RPCMessages/GroupCreateResponse.cs
RPCMessages/GroupInviteResponse.cs
RPCMessages/GroupKickResponse.cs
RPCMessages/GroupLeaveResponse.cs
RPCMessages/GroupMarkResponse.cs
RPCMessages/GroupOpenResponse.cs
RPCMessages/GroupRenameResponse.cs
RPCMessages/GroupResponse.cs
RPCMessages/GroupSetPurposeResponse.cs
RPCMessages/GroupSetTopicResponse.cs
RPCMessages/GroupUnarchiveResponse.cs
RPCMessages/MarkResponse.cs
Response.cs
SlackAPI.csproj
SlackClient.cs

Fix channel.mark RequestPath bug
Add is_channel to Channel object
Update Response object to return reason-code as string
Add filetype to UploadFile

Add Group object and various Groups methods

---

JavascriptDateTimeConverter.cs

The `double.Parse()` method parses strings according to the current system's culture, so parsing varies between many different devices. Some cultures can lead to wrong parsing, such as disregard of the decimal point.
This can lead to connection problems, such as when JSON data for `LoginResponse` is being deserialized, the `DateTime` class throws an `OverflowException`, which gets swallowed by the HTTP request callbacks used to fetch the response data for some reason, causing the connection to appear to fail on some cultures.

Fixed JSON not parsing DateTime correctly

---

TeamPreferences.cs

This fixes an exception generated by the JSON deserializer when trying to connect to a team that uses SAML authentication. Including this in the enumeration allows it to deserialize without a problem.

SAML/SSO Support in JSON Deserialization

---

SlackSocketClient.cs

Fixes a subsequent issue found after the fixing of Issue #8

Fix Connect action order causing null underlying socket

---

IntegrationTest/Connect.cs

The Assert.AreEqual takes expected_and then_ actual -- it matters because of the failure messages.

Fix test Asserts :-)

---

Attachment.cs
RPCMessages/ChannelSetTopicResponse.cs
RequestStateForTask.cs
SlackAPI.csproj
SlackTaskClient.cs

In the current implementation a message bigger than 4kb breaks as it tries to send all the information as get parameters.
- I changed it to use post (and fixed the post message building).
- Added Channel Set Topic to SlackTaskClient.
- Added missing attributes in Attachment.

Add attachment tags, task.settopic and change get to post

---

SlackSocketClient.cs

Using this SendMessage method, bots can change the display name that shows up to indicate, for instance, where they got the information from. This change breaks nothing, because by default the name will still be `MySelf.id` but now you can set it properly if you need to.

Add optional username to SendMessage

---

Attachment.cs
IntegrationTest/Helpers/InSync.cs
IntegrationTest/Helpers/SlackMother.cs
IntegrationTest/IntegrationTest.csproj
IntegrationTest/PostMessage.cs
IntegrationTest/Update.cs
RPCMessages/PostMessageResponse.cs
RPCMessages/UpdateResponse.cs
SlackAPI.csproj
SlackClient.cs

1. Attachments extended with all supported field, also fixed Prefix capitalization
2. PostMessage response extended with additional details being provided by Slack API
3. Implemented API call for chat.update
4. Implemented integration tests for both postMessage and update calls.
5. Refactored sync handling via manual reset event for greater test readability.

Improved chat.postMessage, implemented chat.update

---

SlackSocket.cs

I noticed sometimes I can receive a GUID for reply_to instead a int. In this case, the code raises a JsonReaderException and this exception is not properly catched
Fault message example:
```
{
"reply_to":"F17CFFB0-F9A2-48F0-A91E-0545D758E8FC",
"type":"message",
"channel":"C03NT48S9",
"user":"U03MSJ74C",
"text":"My text",
"ts":"1466079251.000320"
}
```

Catch more general Json exception

---

Channel.cs
Conversation.cs
DirectMessageConversation.cs
SlackAPI.csproj
SlackClient.cs

I added this mostly for my own uses for looking up any kind of conversation by ID, but realized it may be a useful change. Also DirectMessageConversation and Channel have a lot of identical fields.

Added Conversation Class and ConversationLookup Field for SlackClient

---

Extensions.cs

(follow-up for #74 )
Changed .ToString("G17") to .ToString("F6") . Works the same as "0.000000" as far as I've tested.
Removed trimming of trailing zeros as we/Slack (now) want six decimal places in timestamp, even if the sixth digit is a zero.

G17 to F6 and removed trimming of trailing zeroes

---

SlackAPI/SlackSocketClient.cs
SlackAPI/WebSocketMessages/GroupLeft.cs

Fixes #96 
**Files changed are:**
**1. SlackSocketClient.cs** - Fetched channelId
**2. GroupLeft.cs** - Updated the type from Channel to string.

Resolved Exception when Bot leaves Slack group

---

build.cake

Replace branch name with pr prefix in CI build.
Don't try to publish PR artifacts

Improved PR support with CI

---

SlackAPI/RPCMessages/SearchResponseFiles.cs
SlackAPI/RPCMessages/SearchResponseMessages.cs
SlackAPI/SlackClient.cs
SlackAPI/SlackSocket.cs
SlackAPI/SlackSocketClient.cs
SlackAPI/SlackTaskClient.cs

Clean up warnings

---

SlackAPI.Tests/SlackAPI.Tests.csproj
SlackAPI.Tests/Users.cs
SlackAPI/RPCMessages/PostEphemeralResponse.cs
SlackAPI/SlackAPI.csproj
SlackAPI/SlackClient.cs
SlackAPI/SlackSocket.cs
SlackAPI/WebSocketMessages/NewMessage.cs

Applied and fixed PR #135 
- Added support of netstandard 2.0 to avoid a warning message when using SlackAPI in netcore2.0
- Added bot_message return values
- Added ephemeral messaging
Fixed #136 
- Added attachments proeprty

Fixed merge conflict for PR #135 + fix for #136

---

SlackAPI.Tests/Configuration/IntegrationFixture.cs
SlackAPI.Tests/Connect.cs
SlackAPI.Tests/UserUIInteraction.cs
SlackAPI/SlackClient.cs
SlackAPI/SlackClientBase.cs
SlackAPI/SlackClientHelpers.cs
SlackAPI/SlackSocket.cs
SlackAPI/SlackSocketClient.cs
SlackAPI/SlackTaskClient.cs

This PR introduces full proxy support for SlackClient, SlackTaskClient and SlackSocketClient and supersede #133.
I had to do some changes and API breaks to be able to pass a IWebProxy instance in SlackClient/SlackTaskClient and SlackSocketClient constructors. Most of the changes are only code move. I added comments on real changes
- SlackClientBase is created and contains generic web access methods (HttpWebRequest/HttpClient with proxy support)
- SlackClient and SlackTaskClient inherit SlackClientBase
- SlackSocket is updated with proxy support
- [API BREAK] SlackSocketHelpers class is created and contains the old public static methods from SlackClient converted to instance methods. I also added asyncsuffix on FindTeam and AuthSign methods
Because of these changes, I think the next …

Added full proxy support

---

SlackAPI/Extensions.cs
SlackAPI/JavascriptDateTimeConverter.cs

This should fix #170. The changes are:
* Using invariant culture to serialize timestamps
* Corresponding change to the Assert expression (the expression relates on the timestamp serialization options).

Fixes timestamp serialization issue (#170)

---

SlackAPI/RPCMessages/AccessTokenResponse.cs

The bot class referenced by the AccessTokenResponse had been made specific to the user pull and no longer reflected the access token response returned from slack

Updated AccessTokenResponse to include the BotTokenResponse and team_id

---

SlackAPI/RPCMessages/SearchResponseMessages.cs

Currently this error is thrown when ConnectAsync is called:
> Error converting value "not_set" to type 'SlackAPI.SearchSort'. Path 'self.prefs.search_sort', line 1, position 336.
This is due to Slack adding new sort option called not_set to it's API. This commit introduces this new sort type to this library.

Added not_set to SearchSort to make the library able to connect to Slack again

---

SlackAPI/RPCMessages/SearchResponseMessages.cs

When you create a new user and hook up to Slack using this library, I get a similar error as in https://github.com/Inumedia/SlackAPI/issues/177 but with `not_set_new_user` instead. This PR fixes this error by adding the `not_set_new_user` enum to the `SearchResponseMessages` class.

Added not_set_new_user enum

---

SlackAPI/RPCMessages/ChannelInviteResponse.cs
SlackAPI/SlackClient.cs
SlackAPI/SlackTaskClient.cs

This adds the ability to call [channels.invite](https://api.slack.com/methods/channels.invite)
Closes #195

Adds channels.invite API request

---

SlackAPI.Tests/Configuration/IntegrationFixture.cs
SlackAPI.Tests/Connect.cs
SlackAPI/SlackSocketClient.cs
SlackAPI/WebSocketMessages/ManualPresenceChange.cs
SlackAPI/WebSocketMessages/PresenceChange.cs
SlackAPI/WebSocketMessages/PresenceChangeSubscription.cs

Presence changes support is broken in SlackApi probably because of changes on Slack in January 2018 (https://api.slack.com/events/presence_change).
- I introduced a flag in the ctor to synchronize presence changes in the users lookup table. It's an opt-in option because it can have a negative impact on performance.
- I introduced a `SubscribePresenceChange` method to subscribe changes only for specific users
- I added `OnPresenceChanged` event
- I added support of `manual_presence_change` event (same `OnPresenceChanged` event is raised)
- I fixed the `SendPresence` method (the argument was not used)
- I added few unit tests

Fixed presence_changed support

---

SlackAPI.Tests/Configuration/IntegrationFixture.cs
SlackAPI.Tests/Connect.cs
SlackAPI.Tests/Helpers/InSync.cs
SlackAPI.Tests/SlackAPI.Tests.csproj
SlackAPI.Tests/UserUIInteraction.cs
SlackAPI/RPCMessages/PresenseResponse.cs

Fixed unit tests:
- Selenium test because Slack website has changed
- PresenceChanged unit tests were not stable
- Used Polly to retry connection when Slack API return ratelimited error
- Added `Presence.auto` enum value because Slack API doesn't support 'active' status (https://api.slack.com/methods/users.setPresence)

Unit-tests fixes + reliability

---

SlackAPI/SlackTaskClient.cs

Per https://api.slack.com/methods/chat.postMessage#arguments :
The `as_user` parameter may not be used with newer bot tokens. For such newer tokens, whenever `as_user` is supplied, the request will fail with "invalid_arguments" (even when false). 
As the default is false we can only provide it if it's set to true, and it should still preserve compatibility.

Only provide as_user parameter if set to true

---

SlackAPI/SlackTaskClient.cs

The ability to update blocks is provided by the API: https://api.slack.com/methods/chat.update

Add blocks parameter to UpdateAsync

---

SlackAPI.Tests/UserUIInteraction.cs
SlackAPI/SlackClientBase.cs

According #218 and https://slack.com/intl/en-sg/help/articles/360024438834-Transport-Layer-Security--TLS--in-Slack , TLS 1.0 and 1.1 are not supported anymore by Slack

Force TLS1.2 support as requested by Slack

---

SlackAPI/SlackClient.cs
SlackAPI/SlackTaskClient.cs

unfurl_links is only included in API request if set to `true`. Because Slack will do some unfurling by default unless you explicitly tell them not to, we should have a way of providing this.

Allow explicit unfurl_links = false

---

.gitignore
Directory.Build.props
GlobalAssemblyInfo.cs
SlackAPI.Tests/SlackAPI.Tests.csproj
SlackAPI.sln
SlackAPI/SlackAPI.csproj
build.cake
tools/packages.config

I noticed the version in the SlackAPI assembly version doesn't match the nuget version.
I changed the Cake script to use GitVersion to automatically generate the version (instead of using the version from Directory.Build.props). To bump the version, you just have to add a tag once a version is released (https://gitversion.readthedocs.io/en/latest/input/docs/more-info/version-increments/).

Used GitVersion to generate versions

---

.gitignore
Directory.Build.props
GlobalAssemblyInfo.cs
SlackAPI.Tests/SlackAPI.Tests.csproj
SlackAPI.sln
SlackAPI/Request.cs
SlackAPI/SlackAPI.csproj
SlackAPI/SlackClientBase.cs
SlackAPI/SlackSocket.cs
build.cake
tools/packages.config

I removed netstandard1.3 and netstandard1.6 because of the new TLS1.2 Slack requirement.
This PR is dependent of the GitVersion PR #223 because I bumped the version to 1.2.0 (using specific commit message)

Removed obsolete netstandrd1.3 and netstandard1.6

---

SlackAPI/RPCMessages/UserEmailLookupResponse.cs
SlackAPI/SlackClient.cs
SlackAPI/SlackTaskClient.cs

Hello
Thank you for creating this library! I'm using it in one of my projects and it's been very helpful. 
I was needing to make the following request [users.lookupByEmail](https://api.slack.com/methods/users.lookupByEmail) and noticed that the project doesn't have it implemented. 
So,  instead of opening an issue, I decided to include it myself.
Let me know if I need to do anything else to merge this pull request.

Adding users.lookupByEmail request method

---

SlackAPI/Response.cs

Some time when we have a connection failure, the error message need some information, ex: missing_scope
So we need to know what are the "needed" scope to add them.
with provided we can see what are the permission that we already provided to app.

Add the attribute needed, provided

---

SlackAPI/SlackSocketClient.cs

When the api stay running and there is for some reason a connection failure.
The SlackSocketClient is disconnected.
What I added is: An event to be notified when the connection is lost.
So,
After that we can retry to connect again :).

Add event for ConnectionLost

---

SlackAPI/TeamPreferences.cs

We're seeing this cause json deserialization exceptions when calling `SlackClient.ConnectAsync()` on one of our projects
`Error converting value {null} to type 'System.Boolean'. Path 'team.prefs.stats_only_admins'`

Make stats_only_admins a nullable bool

---

SlackAPI.sln
SlackAPI/RPCMessages/ConversationsListResponse.cs
SlackAPI/Response.cs
SlackAPI/SlackClient.cs
SlackAPI/SlackTaskClient.cs

Resolves Issue #242 
Resolves original bug identified in Pull Request #231

Added conversations.list endpoint functionality and cursor request parameter functionality in base response class.

---

SlackAPI/RPCMessages/JoinDirectMessageChannelResponse.cs
SlackAPI/SlackClient.cs

Slack is deprecating the im API.  This changes the direct message opening and sending to work through the conversations API instead.
Note: Additional changes should be made for other APIs that are being deprecated, but this was the only parts I was able to get time to fix.

Change im to use Conversations API.  DM API is being deprecated.

---

SlackAPI.Tests/Conversations.cs
SlackAPI.Tests/UserUIInteraction.cs
SlackAPI/Channel.cs
SlackAPI/SlackClient.cs
SlackAPI/SlackClientBase.cs
SlackAPI/SlackTaskClient.cs

fixed auth with the token
added conversation list test
added is_im property
added user property to channel
fixed upload file method
fixed UserUIInteraction test

Auth feature

---

SlackAPI/Message.cs

There is an attachments field in the response of the messages from Slack.
( see: https://api.slack.com/methods/conversations.history#responses )
However, the field does not exist in Message class.

Added attachments field to Message class

---

SlackAPI/SlackClient.cs
SlackAPI/SlackTaskClient.cs

**Overview:**
when trying to schedule a message, and specify the date , you get a invalid argument error , and the issue is that the `post_at` is expected to be a string number, however the `TimeSpan.TotalSeconds` return a double type which when converted to string preserve the precision , which is not valid
The fix is to convert the double to an int to get ride of the precision which causing the issue.

Fix the post_at parameter
