README.md, SlackAPI.csproj, SlackAPI.nuspec
I added a NuSpec file to the project. There is an outdated NuGet package at nuget.org. It'd be very nice if new versions could somehow be regularly pushed.
=> Added nuspec file

IntegrationTest/Connect.cs, SlackAPI.csproj, SlackSocketClient.cs, WebSocketMessages/ChannelArchive.cs, WebSocketMessages/ChannelCreated.cs, WebSocketMessages/ChannelDeleted.cs, WebSocketMessages/ChannelRename.cs, WebSocketMessages/ChannelUnarchive.cs, WebSocketMessages/GroupArchive.cs, WebSocketMessages/GroupClose.cs, WebSocketMessages/GroupJoined.cs, WebSocketMessages/GroupLeft.cs, WebSocketMessages/GroupOpen.cs, WebSocketMessages/GroupRename.cs, WebSocketMessages/GroupUnarchive.cs, WebSocketMessages/TeamJoin.cs, WebSocketMessages/Typing.cs, WebSocketMessages/UserChange.cs
This handles more RTM messages and handles channel, group and user updates.
This should help fix #15
=> Add more websocket messages, better handle changes

ContextMessage.cs, RPCMessages/AccessTokenResponse.cs, Request.cs, RequestStateForTask.cs, Response.cs, SlackAPI.csproj, SlackAPI.sln, SlackApi.Console/App.config, SlackApi.Console/Program.cs, SlackApi.Console/Properties/AssemblyInfo.cs, SlackApi.Console/SlackApi.Console.csproj, SlackClient.cs, SlackScope.cs, SlackTaskClient.cs
Hi -- I've implemented OAuth in the API according to the instructions on https://api.slack.com/docs/oauth.
There is a little console app that shows how it works. You'll need to change the clientId, clientSecret, and redirectUri values as per the app that you need to register at api.slack.com.
=> Implemented OAuth

.gitignore, .vs/config/applicationhost.config, IntegrationTest/Configuration/Config.cs, IntegrationTest/Configuration/SlackConfig.cs, IntegrationTest/Configuration/config.default.json, IntegrationTest/Connect.cs, IntegrationTest/Helpers/ClientHelper.cs, IntegrationTest/IntegrationTest.csproj, IntegrationTest/JoinDirectMessageChannel.cs, IntegrationTest/packages.config, RPCMessages/JoinDirectMessageChannelResponse.cs, SlackAPI.csproj, SlackAPI.sln, SlackClient.cs
Added a method (+ test refactor) to be able to join a DM channel. The Response then contains the DM channel name.
Note: Moved out keys and sensitive names into config file that is ignored from git found under \SlackAPI\IntegrationTest\Configuration\config.json
=> Join direct message channel

Attachment.cs
Adding additional attachment fields as described here
https://api.slack.com/docs/attachments
=> Attachment Model Updated

SlackAPI.sln
Just a simple tweak to make finding these easier :stuck_out_tongue:
=> Add docs in a solution folder for easier editing

RPCMessages/ChannelCreateResponse.cs, SlackAPI.csproj, SlackClient.cs
=> Channels Create Method

Preferences.cs
Fixed typo in highlight_words property
=> Fixed highlight_words typo

SlackClient.cs, SlackScope.cs
Avoid crash if some parameters are null when requesting OAuth url (for example a null team parameter)
Added Flags to flags enum
=> Small changes related to OAuth authentication process

Extensions.cs, Request.cs, RequestStateForTask.cs, SlackClient.cs, SlackSocket.cs
Added Deserialize/Deserialize<K> extension methods to centralized deserialization options
Allow registration of external JsonConverter
Client can register custom JSonConverter. It allows to access raw data if requested or to provide additional logic
=> Added Deserialize/Deserialize<K> extension method

IntegrationTest/Connect.cs, SlackAPI.nuspec, appveyor.yml
Configured CI with appveyor.yml file
Disabled TestGetAccessToken test
Updated Newtonsoft.Json dependency to 9.0.1 in nuspec file
=> AppVeyor integration

IntegrationTest/Connect.cs, IntegrationTest/Helpers/ClientHelper.cs, IntegrationTest/Helpers/InSync.cs, IntegrationTest/IntegrationTest.csproj, IntegrationTest/JoinDirectMessageChannel.cs, IntegrationTest/PostMessage.cs, IntegrationTest/Update.cs, IntegrationTest/packages.config, packages.config
Based on `feature/ci` branch
- Removed Polly dependency.
- Updated tests and used InSync helper (replaced old Polly code and infinite WaitHandle).
- Added 5 seconds timeout in InSync helper
- Removed unused WebSocket4Net dependency
=> Clean tests

Attachment.cs, IntegrationTest/Helpers/SlackMother.cs, IntegrationTest/PostMessage.cs, SlackClient.cs
This adds the ability to send message buttons. 
https://api.slack.com/docs/message-buttons
=> Add ability to send button actions on an attachment.

SlackAPI/Attachment.cs
add `callback_id` field for `message-buttons` feature.
https://api.slack.com/docs/message-buttons
=> add `callback_id`

SlackAPI/SlackClient.cs, SlackAPI/SlackSocketClient.cs, SlackAPI/WebSocketMessages/NewMessage.cs
If there's no valid login data, below code will throw an exception. So user can't receive any callback response.
https://github.com/Inumedia/SlackAPI/blob/master/SlackAPI/SlackSocket.cs#L69
=> check result before making a websocket connection

SlackAPI/SlackClient.cs, SlackAPI/SlackSocketClient.cs, SlackAPI/WebSocketMessages/NewMessage.cs
https://api.slack.com/docs/message-threading
=> add `thread_ts` for MessageThreading

SlackAPI/SlackSocket.cs
When included in a larger project, there are times when not all assemblies can be loaded. This would cause a loader exception within the static initializer which is likely not the intended outcome. Not sure if there's a better way to check if an assembly can be reflected on other  than a try/catch.
=> GetTypes Error in Static Initializer of SlackSocket

SlackAPI/TeamPreferences.cs
Based on issue https://github.com/Inumedia/SlackAPI/issues/116
=> Added support for Slack Google authentication

SlackAPI/UserProfile.cs
Adding new status fields to UserProfile.cs to support Slack's new status feature. 
https://api.slack.com/docs/presence-and-status
=> Add new status fields

SlackAPI.Tests/SlackAPI.Tests.csproj, SlackAPI.Tests/Users.cs, SlackAPI/User.cs
This adds some missing properties to the `User` object which are exposed by the `users.list` endpoint.
I threw in a simple integration test as well, but creating `restricted`/`ultra_restricted` users requires a paid plan so I'm not sure what else I can add to it. Suggestions are welcome.
=> Add some properties to the user object

SlackAPI/Attachment.cs
Footer text and image URL added to attachment
=> Footer support

SlackAPI.Tests/PostMessage.cs, SlackAPI.Tests/Timestamp.cs, SlackAPI.Tests/Update.cs
Cleanup in tests to avoid compilation warning.
This PR can be applied alongside with #100
=> Clean warnings in test project

SlackAPI/SlackAPI.csproj
Removed an unused reference for netstandard1.3
=> Clean project references needed by platforms

SlackAPI/RPCMessages/SearchResponseFiles.cs
=> Added files property in SearchResponseFiles

SlackAPI/SlackClient.cs
Fixed merge conflict for PR #134
=> Fixed merge conflict for PR #134 (as_user is an optional parameter)

Directory.Build.props
A version marked 1.0.6 was already available on MyGet so I bumped version to avoid breaking things for existing users
=> Bump version to 1.0.7 

SlackAPI/Block.cs, SlackAPI/SlackClient.cs, SlackAPI/SlackTaskClient.cs, SlackAPI/WebSocketMessages/NewMessage.cs
adding support for Slack's new and preferred block layout api
=> Block message layout support

SlackAPI/SlackTaskClient.cs
Trying to resolve #164.
Not tested but should work as the new methods are simply copied from SlackClient.cs.
=> Synced exposing async apis with SlackClient

SlackAPI.Tests/BlockMessage.cs, SlackAPI.Tests/Helpers/SlackMother.cs, SlackAPI/Block.cs, SlackAPI/SlackClient.cs, SlackAPI/SlackTaskClient.cs
Along with the tests, I added streamlined Block and Element objects containing just the necessary fields
=> Block messages tests and streamlined objects

SlackAPI/Request.cs
=> Update RequestPath to use ConcurrentDictionary to mitigate threading issues

SlackAPI.Tests/BlockMessage.cs, SlackAPI/Attachment.cs
=> Added blocks field to attachment

SlackAPI/Block.cs
This is a really simple fix for #205.
=> Fix UserSelect type identifier

SlackAPI/JavascriptDateTimeConverter.cs, SlackAPI/Message.cs, SlackAPI/RPCMessages/MessageHistory.cs, SlackAPI/SlackClient.cs, SlackAPI/SlackTaskClient.cs, build.cake
- Added unread_count_display field on MessageHistory.
- Added thread_ts field on message. 
- Re-enabled tests
=> Added fields (unread_count_display, thread_ts)

SlackAPI.Tests/Connect.cs
- Properly close sockets at the end of each test
- Add extra delay between each test in Connect test class (to mitigate Slack API throttling)
=> Mitigate timeout issues in Unit Tests

SlackAPI/SlackClientBase.cs
Our organization uses proxies to access the Slack API. We need the ability to edit the address.
=> Editable APIBaseLocation in SlackClientBase

SlackAPI/Preferences.cs
muted_channels was missing in the preferences object
=> Added muted_channels to the preferences

SlackAPI/Attachment.cs
=> Add missing URL property in AttachmentAction

SlackAPI/SlackSocketClient.cs
Removed unused type parameters in SlackSocketClient class.
=> Remove unused type parameters

SlackAPI/RequestStateForTask.cs, SlackAPI/SlackSocket.cs, SlackAPI/SlackTaskClient.cs
I have some lock on framework. It's PR fix it
=> Fix for lock async methods on framework

SlackAPI/Block.cs
Adds HeaderBlock type for messages
=> Added HeaderBlock type

SlackAPI/RPCMessages/ScheduleMessageResponse.cs, SlackAPI/SlackClient.cs, SlackAPI/SlackTaskClient.cs
Adds support for chat.scheduleMessage. 
https://api.slack.com/messaging/scheduling
=> Scheduled message

SlackAPI/RPCMessages/ConversationsOpenResponse.cs, SlackAPI/SlackTaskClient.cs
=> Add support for multi-person DMs

SlackAPI/UserProfile.cs
Change
- Add title and display_name fields to UserProfile class
=> Add title and display_name fields to UserProfile class

SlackAPI/SlackTaskClient.cs
Addresses https://github.com/Inumedia/SlackAPI/issues/301
We've already implemented this to our mirror and it seems to work as expected
=> updated GetUserListAsync with optional arguments

SlackAPI/SlackClient.cs, SlackAPI/SlackTaskClient.cs
=> Don't post as_user unless specified.

SlackAPI/RPCMessages/ConversationsJoinResponse.cs, SlackAPI/Response.cs, SlackAPI/SlackClient.cs, SlackAPI/SlackTaskClient.cs
=> conversations.join
